function Unew = handleU( Uold, med_p, var_p )
%HANDLEU Generates a new U vc with mean and variance as specified.
    % Requires an U vc generated by rand(1,T) only!!!!

    medUold = mean(Uold);
    varUold = var(Uold);
    %Unew = Uold + ( med_p - medUold );

    new_b_a = sqrt ( 12 * var_p  );  % relazione nata da integrali - è un momento
    
    new_b = med_p + (new_b_a)/2;
    new_a = med_p - (new_b_a)/2;

    Unew = ( Uold * (new_b-new_a) ) + new_a;
    
end

