function molla_pendolo(tn,un)
%
%   rappresentazione grafica del sistema
%   molla corpo pendolo
%
%     uso: molla_pendolo(tn,un)
% 
%     Input: tn= vettore dei tempi
%            un= array con almeno due vettori colonna (o riga)
%                contenenti le posizioni delle 2 masse ai tempi tn. 
%
[n1,n2]=size(un);
if n1>n2
    un=un';
end

% preparo le variabili 
%xmin=min(min(un(1:2,:)));xmax=max(max(un(1:2,:))); xr=(xmax-xmin)/5;
xmin=-3;xmax=3; xr=0;
ymin=-3;ymax=3; yr=0;
xmin=xmin-xr; xmax=xmax+xr;
ymin=ymin-yr; ymax=ymax+yr;

    figNumber=figure( ...
        'Name','Molla pendolo', ...
        'Visible','on');
    colordef(figNumber,'white');
    axes( ...
        'Units','normalized', ...
        'Visible','on');

    axis([-1 1 -1 1]);
    axHndl=gca;
    figNumber=gcf;
    set(axHndl, ...
        'XLim',[xmin xmax],'YLim',[ymin ymax], ...
        'Drawmode','fast', ...
        'Visible','on', ...
        'NextPlot','add', ...
        'View',[0,90]);
    tempo=text('position',[3,0.6,0],...
            'String',[],...
            'Fontsize',14);
        molla=line( ...
            'color','g', ...
            'Linewidth',2,...
            'erase','normal', ...
            'xdata',[],'ydata',[]);
        parete=line( ...
            'color','k', ...
            'Linewidth',3,...
            'erase','none', ...
            'xdata',[],'ydata',[]);
        massa = line( ...
            'color','r', ...
            'Marker','s', ...
            'markersize',9, ...
            'markerfacecolor','r', ...
            'markeredgecolor','r', ...
            'erase','normal', ...
            'xdata',[],'ydata',[]);
        asta=line( ...
            'color','g', ...
            'Linewidth',2,...
            'erase','normal', ...
            'xdata',[],'ydata',[]);
        pendolo = line( ...
            'color','b', ...
            'Marker','o', ...
            'markersize',9, ...
            'markerfacecolor','b', ...
            'markeredgecolor','b', ...
            'erase','normal', ...
            'xdata',[],'ydata',[]);
         
l=length(tn);
for k=1:l
    % punti molla
    x1=linspace(un(1,k),3,15);
    y1=[0,0,.1,-.1,.1,-.1,.1,-.1,.1,-.1,.1,-.1,.1,0,0];
    set(tempo,'String',['t=',num2str(tn(k))]);
    set(parete,'xdata',[3,3],'ydata',[-0.5,0.5]);
    set(massa,'xdata',un(1,k),'ydata',0);
    set(molla,'xdata',x1,'ydata',y1);
    xp=un(1,k)+sin(un(2,k)); yp=-cos(un(2,k));
    set(asta,'xdata',[un(1,k),xp],'ydata',[0,yp]);
    set(pendolo,'xdata',xp,'ydata',yp);
    
    
    drawnow;
end
